const myArray = [ true, null]

console.log (myArray)
myArray.push('5',67,100)
console.log(myArray)
myArray.shift()
console.log(myArray)
myArray.unshift(100)
console.log(myArray)
myArray.unshift(9)
myArray.push(9)
console.log(myArray)
myArray.pop(myArray)
myArray.shift()
console.log(myArray)
